options(stringsAsFactors=FALSE)
if(.Platform$OS.type=="windows")windowsFonts(Arial=windowsFont("Arial"))
root<-Sys.getenv("HCC_PROJECT_ROOT",unset="");if(!nzchar(root))root<-normalizePath(".",winslash="/",mustWork=TRUE)
outdir<-Sys.getenv("HCC_OUTPUT_DIR",unset="");if(!nzchar(outdir))outdir<-file.path(root,"07_figures");dir.create(outdir,recursive=TRUE,showWarnings=FALSE)
boot<-read.csv(file.path(root,"06_results","prjeb54571_key_median_difference_bootstrap_ci.csv"))
loo<-read.csv(file.path(root,"06_results","prjeb54571_escherichia_shigella_leave_one_cirrhosis_out.csv"))
met<-read.csv(file.path(root,"06_results","integration","figure3_mtbls8764_four_model_robustness.csv"))
legacy<-read.csv(file.path(root,"06_results","prjeb54571_host_rnaseq_historical_target_overlap.csv"))
pseudo<-read.csv(file.path(root,"06_results","microbiome_cross_cohort","pseudocount_sensitivity_summary.csv"),check.names=FALSE)
filters<-data.frame(layer=c("Microbiome","Microbiome","Microbiome","Bulk RNA","Bulk RNA","Tissue metabolome","Tissue metabolome"),stage=c("ASVs","genus aggregates","prevalence/abundance pass","input genes","count-filter pass","raw features","all-pair QC pass"),n=c(6834,232,87,60708,16850,3606,615))
corrections<-data.frame(item=c("Duplicate faecal library","Single-cell ambient RNA","PRJNA647523","PRJNA540574","ST004733"),action=c("1 excluded; 105 patients retained","cell-type-restricted scoring; no algorithmic correction","summary evidence only","excluded from patient-level pooling","formally unavailable/excluded"),reason=c("one library per patient","limit hepatocyte transcript leakage into immune programmes","no harmonisable participant matrix","disease labels unresolved","sample-level files unavailable"))
metflow<-data.frame(stage=c("High-coverage candidates","All four models converged","Direction consistent","Exploratory screen pass"),n=c(nrow(met),sum(met$all_models_converged),sum(met$direction_consistent_four_models),sum(met$longitudinal_promotion)))
write.csv(filters,file.path(outdir,"SupplementaryFigure1_source_data_filter_flows.csv"),row.names=FALSE)
write.csv(corrections,file.path(outdir,"SupplementaryFigure1_source_data_correction_ledger.csv"),row.names=FALSE)
write.csv(metflow,file.path(outdir,"SupplementaryFigure1_source_data_metabolite_model_flow.csv"),row.names=FALSE)
write.csv(pseudo,file.path(outdir,"SupplementaryFigure1_source_data_pseudocount_small_k_sensitivity.csv"),row.names=FALSE)

draw<-function(){
 layout(matrix(1:8,4,2,byrow=TRUE),heights=c(1,1,1,1),widths=c(1,1));par(family="Arial",fg="#222222")
 # a filters
 par(mar=c(1,1,2,1));plot.new();plot.window(c(0,1),c(0,1));title("Feature filters retain traceable denominators",adj=.03,cex.main=.88,font.main=2,line=.55)
 groups<-split(filters,filters$layer);ys<-c(.79,.50,.21);for(j in seq_along(groups)){z<-groups[[j]];xx<-seq(.16,.84,length.out=nrow(z));for(i in seq_len(nrow(z))){rect(xx[i]-.10,ys[j]-.075,xx[i]+.10,ys[j]+.075,col="#EFF3F4",border="#6F8794");text(xx[i],ys[j]+.025,z$n[i],font=2,cex=.62,col="#365A6C");text(xx[i],ys[j]-.03,z$stage[i],cex=.43);if(i<nrow(z))arrows(xx[i]+.10,ys[j],xx[i+1]-.10,ys[j],length=.05,col="#777777")};text(.02,ys[j],names(groups)[j],adj=0,srt=90,font=2,cex=.46)};mtext("A",3,line=1.35,at=0,adj=0,font=2,cex=1.05)
 # b bootstrap
 par(mar=c(4,6.3,2,1));labs<-c(observed_asvs="Observed ASVs",shannon="Shannon diversity",escherichia_shigella_clr="Escherichia-Shigella CLR");yy<-1:nrow(boot);plot(boot$median_difference_HCC_minus_Cirrhosis,yy,xlim=range(c(boot$bootstrap_95_ci_low,boot$bootstrap_95_ci_high)),ylim=c(.5,3.5),yaxt="n",pch=19,col="#3A7D6B",xlab="HCC-minus-cirrhosis median difference",ylab="",cex=.75);segments(boot$bootstrap_95_ci_low,yy,boot$bootstrap_95_ci_high,yy,lwd=2,col="#83AFA2");abline(v=0,lty=2,col="#999999");axis(2,at=yy,labels=labs[boot$metric],las=1,tick=FALSE,cex.axis=.58);title("Ten-thousand-iteration bootstrap intervals retain uncertainty",adj=.03,cex.main=.85,font.main=2,line=.55);mtext("B",3,line=1.35,at=par("usr")[1],adj=0,font=2,cex=1.05)
 # c LOO
 par(mar=c(4,5,2,1));ord<-order(loo$adjusted_beta_HCC);lo_ci<-loo$adjusted_beta_HCC-1.96*loo$adjusted_se;hi_ci<-loo$adjusted_beta_HCC+1.96*loo$adjusted_se;plot(loo$adjusted_beta_HCC[ord],1:nrow(loo),xlim=range(c(lo_ci,hi_ci)),ylim=c(.5,nrow(loo)+.5),yaxt="n",pch=19,col="#4477AA",xlab="Age/aetiology-adjusted HCC coefficient",ylab="",cex=.7);segments(lo_ci[ord],1:nrow(loo),hi_ci[ord],1:nrow(loo),col="#8AB0CD",lwd=1.2);axis(2,at=1:nrow(loo),labels=loo$omitted_cirrhosis_sample[ord],las=1,tick=FALSE,cex.axis=.50);abline(v=0,lty=2,col="#999999");title("Escherichia-Shigella direction survives all 10 comparator omissions",adj=.03,cex.main=.82,font.main=2,line=.55);mtext("C",3,line=1.35,at=par("usr")[1],adj=0,font=2,cex=1.05)
 # d met flow
 par(mar=c(1,1,2,1));plot.new();plot.window(c(0,1),c(0,1));title("Longitudinal metabolite screening is deliberately explicit",adj=.03,cex.main=.86,font.main=2,line=.55);xx<-c(.12,.38,.64,.88);ww<-c(.20,.17,.14,.10);for(i in 1:4){rect(xx[i]-ww[i]/2,.45,xx[i]+ww[i]/2,.69,col=if(i<4)"#EEF3F4" else "#E7F2EE",border=if(i<4)"#6F8794" else "#3A7D6B",lwd=1.2);text(xx[i],.59,metflow$n[i],font=2,cex=.80,col="#365A6C");text(xx[i],.35,metflow$stage[i],cex=.45);if(i<4)arrows(xx[i]+ww[i]/2,.57,xx[i+1]-ww[i+1]/2,.57,length=.05,col="#777777")};text(.50,.14,"Final screen also requires BH q<0.10 in both prespecified GEE analyses",cex=.48,col="#555555");mtext("D",3,line=1.35,at=0,adj=0,font=2,cex=1.05)
 # e legacy
 par(mar=c(4,4.5,2,1));y<--log10(pmax(legacy$padj_BH,1e-300));cc<-ifelse(legacy$primary_DE,"#C95A5A","#AAAAAA");plot(legacy$log2FoldChange,y,pch=19,col=cc,ylim=c(0,max(1.4,max(y))),xlab="Primary log2 fold-change",ylab="-log10(BH q)",cex=.65);abline(v=c(-1,1),lty=3,col="#999999");abline(h=-log10(.05),lty=2,col="#C95A5A");title("Legacy network targets fail transcriptomic validation",adj=.03,cex.main=.87,font.main=2,line=.55);text(par("usr")[1],par("usr")[4],paste0("55 proposed | ",nrow(legacy)," mapped | ",sum(legacy$primary_DE)," primary DE"),adj=c(0,1),cex=.52,font=2,col="#8A3333");mtext("E",3,line=1.35,at=par("usr")[1],adj=0,font=2,cex=1.05)
 # f ledger
 par(mar=c(1,1,2,1));plot.new();plot.window(c(0,1),c(0,1));title("Corrections and exclusions remain visible",adj=.03,cex.main=.88,font.main=2,line=.55);yy<-seq(.84,.16,length.out=nrow(corrections));for(i in 1:nrow(corrections)){rect(.02,yy[i]-.055,.98,yy[i]+.055,col=if(i%%2)"#F7F7F7" else "white",border="#DDDDDD");text(.04,yy[i]+.018,corrections$item[i],adj=0,font=2,cex=.50);text(.42,yy[i]+.018,corrections$action[i],adj=0,cex=.45,col="#8A3333");text(.04,yy[i]-.026,corrections$reason[i],adj=0,cex=.42,col="#555555")};mtext("F",3,line=1.35,at=0,adj=0,font=2,cex=1.05)
 # g pseudocount decision sensitivity
 par(mar=c(4,4.2,2,1));ylim<-c(0,max(pseudo$discovery_q_lt_0_10)+5);plot(pseudo$pseudocount_on_counts,pseudo$discovery_q_lt_0_10,type="b",pch=16,lwd=1.5,col="#4477AA",ylim=ylim,xlab="Pseudocount added to genus counts",ylab="Number of genera",xaxt="n");axis(1,at=pseudo$pseudocount_on_counts);lines(pseudo$pseudocount_on_counts,pseudo$locked_validation_pass,type="b",pch=17,lwd=1.5,col="#D08B35");lines(pseudo$pseudocount_on_counts,pseudo$external_age_adjusted_pass,type="b",pch=15,lwd=1.5,col="#C95A5A");legend("topright",c("Discovery q<0.10","Locked validation","External adjusted"),pch=c(16,17,15),lty=1,col=c("#4477AA","#D08B35","#C95A5A"),bty="n",cex=.45);title("No-Go decision is unchanged by count pseudocount",adj=.03,cex.main=.83,font.main=2,line=.55);mtext("G",3,line=1.35,at=par("usr")[1],adj=0,font=2,cex=1.05)
 # h small-k sensitivity counts
 par(mar=c(4,4.2,2,1));mat<-rbind(pseudo$conventional_dl_all_omissions_p_lt_0_05,pseudo$modified_hksj_all_omissions_p_lt_0_05);bp<-barplot(mat,beside=TRUE,names.arg=pseudo$pseudocount_on_counts,col=c("#83AFA2","#BBBBBB"),border=NA,ylim=c(0,max(mat)+3),xlab="Pseudocount added to genus counts",ylab="All-omission significant genera",cex.names=.60);text(bp,mat+0.6,labels=mat,cex=.55);legend("topright",c("Conventional DL","Modified Hartung-Knapp"),fill=c("#83AFA2","#BBBBBB"),border=NA,bty="n",cex=.45);title("Small-k inference, not direction, removes omission significance",adj=.03,cex.main=.78,font.main=2,line=.55);mtext("H",3,line=1.35,at=par("usr")[1],adj=0,font=2,cex=1.05)
}
base<-file.path(outdir,"SupplementaryFigure1_technical_sensitivity");wmm<-180;hmm<-245;win<-wmm/25.4;hin<-hmm/25.4
if(requireNamespace("svglite",quietly=TRUE))svglite::svglite(paste0(base,".svg"),width=win,height=hin,system_fonts=list(Arial="Arial"),pointsize=8)else svg(paste0(base,".svg"),width=win,height=hin,family="Arial",pointsize=8);par(oma=c(.2,.2,.4,.2));draw();dev.off()
cairo_pdf(paste0(base,".pdf"),width=win,height=hin,family="Arial",pointsize=8);par(oma=c(.2,.2,.4,.2));draw();dev.off()
png(paste0(base,".png"),width=wmm,height=hmm,units="mm",res=600,pointsize=8,family="Arial",bg="white");par(oma=c(.2,.2,.4,.2));draw();dev.off()
tiff(paste0(base,".tiff"),width=wmm,height=hmm,units="mm",res=600,compression="lzw",pointsize=8,family="Arial",bg="white");par(oma=c(.2,.2,.4,.2));draw();dev.off()
