options(stringsAsFactors=FALSE)
root<-Sys.getenv("HCC_PROJECT_ROOT",unset="");if(!nzchar(root))root<-normalizePath(".",winslash="/",mustWork=TRUE)
outdir<-Sys.getenv("HCC_OUTPUT_DIR",unset=file.path(root,"07_figures","q4_information_architecture_redesign"));dir.create(outdir,recursive=TRUE,showWarnings=FALSE)
font<-"Arial";if(.Platform$OS.type=="windows")windowsFonts(Arial=windowsFont("Arial"))
C<-c(ink="#17242B",muted="#66747B",rule="#D8E0E3",pale="#F5F8F9",blue="#2E6F9E",blue_l="#E8F1F7",teal="#31877C",teal_l="#E5F3F0",amber="#B7791F",amber_l="#F8F0DE",violet="#6F5A9B",violet_l="#EEEAF6",red="#B44D4D",red_l="#F8E8E7",green="#397A57",green_l="#E7F2EB")
fd<-file.path(root,"07_figures");rd<-file.path(root,"06_results")
pt<-function(letter,title){
  compact<-c(
    "Genus effects across cohorts"="Cohort effects",
    "Small-k pooled estimates"="Small-k inference",
    "Directional concordance"="Concordance",
    "Promotion sequence"="Promotion gate",
    "Plasma promotions across four models"="Plasma candidates",
    "Paired tissue promotions and identity tier"="Liver tissue",
    "Identification level"="Identity tier",
    "Exact cross-specimen audit"="Cross-specimen gate",
    "Project evidence-state matrix"="Evidence states",
    "Prior-edge provenance by species"="Prior provenance",
    "Weight sensitivity cannot pass the gate"="Weight sensitivity",
    "Provenance gate"="Provenance gate",
    "Cross-dataset host-program direction and effect"="Host concordance",
    "50 patient-matched TCGA pairs"="Matched pairs",
    "Direct external validation"="External validation",
    "Contradiction is retained"="Contradiction",
    "Donor-paired programme effects"="Donor effects",
    "Composition is not an inferential replicate"="Cell composition",
    "Exact sign-flip estimates"="Sign-flip estimates",
    "Global calibration"="Calibration"
  )
  if(title %in% names(compact)) title<-unname(compact[title])
  # Panel meaning is carried by the legend; keeping only the letter prevents
  # title/axis collisions when the composite is reduced to journal width.
  mtext(letter,3,.55,adj=0,font=2,cex=.72,col=C["ink"])
}
short<-function(x,n=24)ifelse(nchar(x)>n,paste0(substr(x,1,n-3),"..."),x)
save4<-function(draw,name,h=150){base<-file.path(outdir,name);w<-180;png(paste0(base,".png"),w,h,units="mm",res=600,pointsize=9,family=font,bg="white");draw();dev.off();tiff(paste0(base,".tiff"),w,h,units="mm",res=600,compression="lzw",pointsize=9,family=font,bg="white");draw();dev.off();cairo_pdf(paste0(base,".pdf"),w/25.4,h/25.4,pointsize=9,family=font);draw();dev.off();if(requireNamespace("svglite",quietly=TRUE)){svglite::svglite(paste0(base,".svg"),w/25.4,h/25.4,pointsize=9,system_fonts=list(sans=font));draw();dev.off()}else{svg(paste0(base,".svg"),w/25.4,h/25.4,pointsize=9,family=font);draw();dev.off()}}
hm<-function(mat,rowlab,collab,lim=NULL){if(is.null(lim))lim=max(abs(mat),na.rm=TRUE);nr<-nrow(mat);nc<-ncol(mat);plot.new();plot.window(c(0,nc),c(0,nr));for(i in 1:nr)for(j in 1:nc){v<-mat[i,j];a<-min(1,abs(v)/lim);base<-if(is.na(v))C["rule"] else if(v>=0)C["red"] else C["blue"];rect(j-1,nr-i,j,nr-i+1,col=if(is.na(v))C["pale"] else paste0(base,sprintf("%02X",round(35+200*a))),border="white");if(!is.na(v))text(j-.5,nr-i+.5,sprintf("%.2f",v),cex=.50,col=if(a>.55)"white" else C["ink"])};axis(2,nr-seq_len(nr)+.5,short(rowlab,30),las=1,tick=FALSE,cex.axis=.58);axis(3,seq_len(nc)-.5,collab,tick=FALSE,cex.axis=.58);box(col=C["rule"])}

# Figure 2
x<-read.csv(file.path(rd,"microbiome_cross_cohort","three_cohort_harmonised_genus_effects.csv"),check.names=FALSE)
ord<-order(abs(x$random_estimate),decreasing=TRUE)[1:18];z<-x[ord,];m2<-as.matrix(z[,c("PRJNA784025_discovery_estimate","PRJNA784025_validation_estimate","age_adjusted_estimate")])
draw2<-function(){par(family=font,oma=c(.15,.15,.15,.15));layout(matrix(c(1,1,2,3,3,4),2,3,byrow=TRUE),widths=c(1.25,1,1),heights=c(1.2,.8));par(mar=c(2.4,8.2,1.4,.5));hm(m2,z$genus,c("Discovery","Locked validation","External adjusted"));pt("A","Genus effects across cohorts");par(mar=c(2.4,7.2,1.4,.7));yy<-seq_len(nrow(z));plot(z$random_estimate,yy,xlim=range(c(z$hksj_ci_low_modified,z$hksj_ci_high_modified),finite=TRUE),ylim=c(.5,nrow(z)+.5),yaxt="n",pch=21,bg=C["teal"],col="white",xlab="Pooled CLR difference",ylab="");segments(z$hksj_ci_low_modified,yy,z$hksj_ci_high_modified,yy,col=C["muted"],lwd=1.2);abline(v=0,lty=2,col=C["rule"]);axis(2,yy,short(z$genus,24),las=1,tick=FALSE,cex.axis=.55);pt("B","Small-k pooled estimates");par(mar=c(2.6,4.5,1.4,.5));tab<-table(rowSums(sign(m2)==sign(x$random_estimate[ord]),na.rm=TRUE));barplot(tab,col=C["blue"],border=NA,xlab="Direction-matched cohorts",ylab="Genera",cex.axis=.65,cex.names=.65);pt("C","Directional concordance");par(mar=c(.8,.8,1.4,.8));plot.new();plot.window(c(0,1),c(0,1));pt("D","Promotion sequence");xx<-c(.12,.38,.64,.88);nn<-c(70,44,30,0);labs<-c("Harmonised","Discovery","Locked validation","External adjusted");for(i in 1:4){col<-if(i<4)C["blue"] else C["red"];symbols(xx[i],.55,rectangles=matrix(c(.17,.25),1),inches=FALSE,add=TRUE,bg=paste0(col,"18"),fg=col);text(xx[i],.58,nn[i],font=2,cex=.85,col=col);text(xx[i],.38,labs[i],cex=.55);if(i<4)arrows(xx[i]+.095,.55,xx[i+1]-.095,.55,length=.04,col=C["muted"])};text(.5,.12,"0/70 meet all prespecified criteria",font=2,cex=.63,col=C["red"])}
save4(draw2,"Figure2_cross_cohort_microbiome_Q4",155)

# Figure 3
pl<-read.csv(file.path(fd,"Figure3_source_data_longitudinal_plasma_promotions.csv"),check.names=FALSE);ti<-read.csv(file.path(fd,"Figure3_source_data_paired_tissue_promotions.csv"),check.names=FALSE);ov<-read.csv(file.path(fd,"Figure3_source_data_exact_cross_specimen_overlap.csv"),check.names=FALSE)
ti<-ti[order(abs(ti$median_log2_difference),decreasing=TRUE),][1:min(12,nrow(ti)),]
draw3<-function(){par(family=font,oma=c(.15,.15,.15,.15));layout(matrix(c(1,1,2,2,3,4),2,3,byrow=TRUE),heights=c(1.15,.85));par(mar=c(2.5,8,1.4,.7));yy<-seq_len(nrow(pl));plot(pl$effect_mid,yy,xlim=range(c(pl$effect_min,pl$effect_max)),ylim=c(.5,nrow(pl)+.5),yaxt="n",pch=21,bg=C["amber"],xlab="Longitudinal model coefficient",ylab="");segments(pl$effect_min,yy,pl$effect_max,yy,lwd=4,col=paste0(C["amber"],"99"));axis(2,yy,short(pl$metabolite,27),las=1,tick=FALSE,cex.axis=.58);abline(v=0,lty=2,col=C["rule"]);pt("A","Plasma promotions across four models");par(mar=c(2.5,7.8,1.4,.7));yy<-seq_len(nrow(ti));plot(ti$median_log2_difference,yy,xlim=range(ti$median_log2_difference),ylim=c(.5,nrow(ti)+.5),yaxt="n",pch=21,bg=ifelse(ti$authentic_standard,C["green"],C["violet"]),xlab="Paired liver median log2 difference",ylab="");segments(0,.5,0,nrow(ti)+.5,lty=2,col=C["rule"]);axis(2,yy,short(ti$metabolite,26),las=1,tick=FALSE,cex.axis=.56);pt("B","Paired tissue promotions and identity tier");par(mar=c(2.6,4.8,1.4,.7));barplot(table(ti$short_tier),las=2,col=c(C["green"],C["violet"]),border=NA,cex.names=.55,ylab="Features");pt("C","Identification level");par(mar=c(.8,.8,1.4,.8));plot.new();plot.window(c(0,1),c(0,1));pt("D","Exact cross-specimen audit");vals<-c(nrow(pl),nrow(ti),sum(ov$direction_concordant,na.rm=TRUE),sum(ov$both_fdr_promoted,na.rm=TRUE));labs<-c("Plasma","Tissue","Direction\nconcordant","Both FDR\npromoted");for(i in 1:4){col<-if(i==4)C["red"] else C["amber"];rect(.06+(i-1)*.235,.35,.22+(i-1)*.235,.70,col=paste0(col,"18"),border=col);text(.14+(i-1)*.235,.58,vals[i],font=2,cex=.88,col=col);text(.14+(i-1)*.235,.43,labs[i],cex=.55)};text(.5,.16,"Specimen-specific signals do not form a validated bridge",cex=.61,font=2,col=C["red"])}
# Correct the four-panel layout: A spans the upper-left two columns, B is
# upper-right, C spans the lower-left two columns, and D is lower-right.
body(draw3)[[3]] <- quote(layout(matrix(c(1,1,2,3,3,4),2,3,byrow=TRUE),heights=c(1.15,.85)))
save4(draw3,"Figure3_human_metabolite_evidence_Q4",190)

# Figure 4
gs<-read.csv(file.path(fd,"Figure4_source_data_gate_scores.csv"),check.names=FALSE);ws<-read.csv(file.path(fd,"Figure4_source_data_weight_sensitivity.csv"),check.names=FALSE);ep<-read.csv(file.path(rd,"provenance_and_portability","gutmgene_provenance_layer.csv"),check.names=FALSE)
gm<-as.matrix(gs[,2:9]);rownames(gm)<-short(gs$candidate_family,33)
draw4<-function(){par(family=font,oma=c(.15,.15,.15,.15));layout(matrix(c(1,1,2,3,3,4),2,3,byrow=TRUE),heights=c(1.1,.9));par(mar=c(5.2,10,1.4,.5));hm(gm,rownames(gm),c("Microbe","Metabolite","M-M link","M-target","Bulk host","Single cell","Contradiction","Robust"),lim=1);pt("A","Project evidence-state matrix");par(mar=c(4.2,5.2,1.4,.5));barplot(table(ep[[1]],ep$evidence_species),beside=FALSE,col=c(C["blue"],C["amber"],C["teal"]),las=2,cex.names=.48,ylab="Traceable prior edges");pt("B","Prior-edge provenance by species");par(mar=c(2.6,8.5,1.4,.7));schemes<-unique(ws$weighting_scheme);cands<-unique(ws$candidate_family);plot(NA,xlim=range(ws$weighted_score),ylim=c(.5,length(cands)+.5),yaxt="n",xlab="Exploratory weighted score",ylab="");for(i in seq_along(cands)){q<-ws[ws$candidate_family==cands[i],];points(q$weighted_score,rep(i,nrow(q)),pch=21,bg=C["amber_l"],col=C["amber"])};axis(2,seq_along(cands),short(cands,28),las=1,tick=FALSE,cex.axis=.55);pt("C","Weight sensitivity cannot pass the gate");par(mar=c(.8,.8,1.4,.8));plot.new();plot.window(c(0,1),c(0,1));pt("D","Provenance gate");items<-c("Project measured","Literature prior","GutMGene v2 bulk verified","Eligible to rescue gate");state<-c("mixed by edge","DOI/PMID locked","NO-GO","NO");for(i in 1:4){col<-if(i<3)C["amber"] else C["red"];rect(.08,.78-i*.15,.92,.88-i*.15,col=paste0(col,"14"),border=col);text(.11,.83-i*.15,items[i],adj=c(0,.5),font=2,cex=.59);text(.89,.83-i*.15,state[i],adj=c(1,.5),cex=.58,col=col)};text(.5,.10,"Database edges remain hypothesis-generating priors",cex=.62,font=2,col=C["red"])}
save4(draw4,"Figure4_provenance_gate_Q4",155)

# Figure 5
s5<-read.csv(file.path(rd,"integration","figure5_host_program_cross_dataset_source.csv"),check.names=FALSE);tc<-read.csv(file.path(fd,"Figure5_source_data_TCGA_paired_differences.csv"),check.names=FALSE);gse<-read.csv(file.path(rd,"GSE63898","host_programs","gse63898_program_validation.csv"),check.names=FALSE)
progs<-unique(s5$program);dsets<-unique(s5$dataset);m5<-matrix(NA,length(progs),length(dsets),dimnames=list(progs,dsets));for(i in 1:nrow(s5))m5[s5$program[i],s5$dataset[i]]<-s5$effect[i]
draw5<-function(){par(family=font,oma=c(.15,.15,.15,.15));layout(matrix(c(1,1,2,3,3,4),2,3,byrow=TRUE),heights=c(1.05,.95));par(mar=c(3,9,1.4,.5));hm(m5,rownames(m5),colnames(m5));pt("A","Cross-dataset host-program direction and effect");par(mar=c(3,5,1.4,.5));boxplot(paired_difference~program,data=tc,las=2,col=C["teal_l"],border=C["teal"],outline=FALSE,cex.axis=.48,ylab="TCGA paired difference");abline(h=0,lty=2,col=C["rule"]);pt("B","50 patient-matched TCGA pairs");par(mar=c(2.8,8.5,1.4,.7));q<-gse[gse$family=="primary_PRJEB54571_GO_programs",];yy<-seq_len(nrow(q));plot(q$plate_adjusted_beta,yy,xlim=range(c(q$plate_adjusted_ci_low,q$plate_adjusted_ci_high)),ylim=c(.5,nrow(q)+.5),yaxt="n",pch=21,bg=ifelse(q$strict_three_dataset_replication,C["green"],C["red"]),xlab="GSE63898 adjusted beta",ylab="");segments(q$plate_adjusted_ci_low,yy,q$plate_adjusted_ci_high,yy,col=C["muted"],lwd=1.3);axis(2,yy,short(q$program,30),las=1,tick=FALSE,cex.axis=.56);abline(v=0,lty=2,col=C["rule"]);pt("C","Direct external validation");par(mar=c(.8,.8,1.4,.8));plot.new();plot.window(c(0,1),c(0,1));pt("D","Contradiction is retained");rect(.10,.40,.42,.70,col=C["green_l"],border=C["green"]);text(.26,.57,"3 programmes\nthree-dataset concordant",font=2,cex=.67,col=C["green"]);rect(.58,.40,.90,.70,col=C["red_l"],border=C["red"]);text(.74,.57,"Respiratory chain\ndirectional contradiction",font=2,cex=.64,col=C["red"]);text(.5,.15,"No numeric pooling across effect measures",cex=.60,col=C["muted"])}
save4(draw5,"Figure5_independent_bulk_host_validation_Q4",155)

# Figure 6
sc<-read.csv(file.path(rd,"single_cell","paired_programs","prespecified_program_paired_results.csv"),check.names=FALSE);sf<-read.csv(file.path(fd,"Figure6_source_data_exact_signflip.csv"),check.names=FALSE);ct<-read.csv(file.path(rd,"single_cell","gse149614_celltype_counts_by_donor_site.csv"),check.names=FALSE);dd<-read.csv(file.path(fd,"Figure6_source_data_donor_paired_differences.csv"),check.names=FALSE)
cts<-unique(sc$celltype);prs<-unique(sc$program);m6<-matrix(NA,length(cts),length(prs),dimnames=list(cts,prs));q6<-m6;for(i in 1:nrow(sc)){m6[sc$celltype[i],sc$program[i]]<-sc$mean_difference[i];q6[sc$celltype[i],sc$program[i]]<-sc$wilcoxon_q_all_modules_sensitivity[i]}
draw6<-function(){par(family=font,oma=c(.15,.15,.15,.15));layout(matrix(c(1,1,2,3,3,4),2,3,byrow=TRUE),heights=c(1.05,.95));par(mar=c(5.5,6.5,1.4,.5));hm(m6,rownames(m6),short(colnames(m6),16));pt("A","Donor-paired programme effects");par(mar=c(4,4.5,1.4,.5));agg<-aggregate(n_cells~celltype+site,ct,sum);mat<-xtabs(n_cells~celltype+site,agg);barplot(t(mat),beside=FALSE,col=c(C["blue"],C["red"]),las=2,cex.names=.48,ylab="Cells (descriptive)");pt("B","Composition is not an inferential replicate");par(mar=c(2.8,8.5,1.4,.7));o<-order(sf$exact_signflip_q_global_bh)[1:min(12,nrow(sf))];qq<-sf[o,];yy<-seq_len(nrow(qq));plot(qq$mean_tumor_minus_normal,yy,xlim=range(c(qq$mean_difference_ci95_low,qq$mean_difference_ci95_high)),ylim=c(.5,nrow(qq)+.5),yaxt="n",pch=21,bg=C["violet"],xlab="Tumour - normal donor-paired mean",ylab="");segments(qq$mean_difference_ci95_low,yy,qq$mean_difference_ci95_high,yy,col=C["muted"],lwd=1.2);axis(2,yy,short(paste(qq$celltype,qq$program,sep=" | "),32),las=1,tick=FALSE,cex.axis=.52);abline(v=0,lty=2,col=C["rule"]);pt("C","Exact sign-flip estimates");par(mar=c(.8,.8,1.4,.8));plot.new();plot.window(c(0,1),c(0,1));pt("D","Global calibration");rect(.10,.43,.40,.70,col=C["violet_l"],border=C["violet"]);text(.25,.57,paste0(nrow(sf)," exact\nsign-flip tests"),font=2,cex=.70,col=C["violet"]);arrows(.43,.56,.57,.56,length=.04,col=C["muted"]);rect(.60,.43,.90,.70,col=C["red_l"],border=C["red"]);text(.75,.57,paste0(sum(sf$exact_signflip_global_fdr_pass=="true")," global-FDR\npasses"),font=2,cex=.70,col=C["red"]);text(.5,.20,paste0("Minimum BH q = ",sprintf("%.3f",min(sf$exact_signflip_q_global_bh,na.rm=TRUE))),font=2,cex=.64,col=C["red"]);text(.5,.10,"Axis-specific localisation remains unsupported",cex=.58,col=C["muted"])}
save4(draw6,"Figure6_single_cell_localisation_Q4",160)
